# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.CharField(max_length=20)),
                ('impuesto', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
            ],
        ),
    ]
